#!/usr/bin/env node
// export-doc.js — turn a Manimo scene DOCUMENT into a runnable, publishable
// scene (HTML + JSX) and upsert its manifest entry.
// ===========================================================================
// The visual builder (ui_kits/builder/) edits a "scene document" — a flat list
// of component instances (see motion/scene-doc.schema.json). Its "Export
// document" button downloads that document as <id>.doc.json. This script
// consumes that file and emits a standalone scene that renders the document
// via motion/render-doc.jsx — the SAME runtime the editor uses, so what you
// built is exactly what ships.
//
// Usage:
//   node scripts/export-doc.js path/to/scene.doc.json
//   node scripts/export-doc.js scene.doc.json --subject ade --id rc-charging
//   node scripts/export-doc.js scene.doc.json --no-manifest
//
// Flags:
//   --subject <id>   subject folder under motion/ (default: doc.subject_id or 'sandbox')
//   --id <id>        scene id (default: doc.id); also the output filename stem
//   --chapter <n>    chapter_number for the manifest entry
//   --no-manifest    write the files but don't touch scene-manifest.json
//
// Unlike scripts/generate-scene.js (spec → bespoke JSX), this is loss-free:
// the document is embedded verbatim and rendered by RenderDoc.

import { resolve, dirname, join } from 'path';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// ── CLI parsing ──────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const opts = { subject: null, id: null, chapter: null, manifest: true };
const positional = [];
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === '--subject') opts.subject = argv[++i];
  else if (a === '--id') opts.id = argv[++i];
  else if (a === '--chapter') opts.chapter = parseInt(argv[++i], 10);
  else if (a === '--no-manifest') opts.manifest = false;
  else positional.push(a);
}

const docPath = positional[0];
if (!docPath) {
  console.error('Usage: node scripts/export-doc.js <doc.json> [--subject id] [--id id] [--chapter n] [--no-manifest]');
  process.exit(1);
}

let doc;
try {
  doc = JSON.parse(readFileSync(resolve(docPath), 'utf8'));
} catch (e) {
  console.error(`Could not read/parse document: ${docPath}\n  ${e.message}`);
  process.exit(1);
}

const id = opts.id || doc.id;
if (!id) { console.error('No scene id (pass --id or set doc.id).'); process.exit(1); }
const subject = opts.subject || doc.subject_id || doc.subjectId || 'sandbox';
const duration = doc.duration;
if (typeof duration !== 'number') { console.error('doc.duration must be a number.'); process.exit(1); }
const title = doc.title || id;

// Normalise the embedded id so the emitted scene is self-consistent.
const embedDoc = { ...doc, id };
const docJson = JSON.stringify(embedDoc, null, 2);

// ── Emit JSX ───────────────────────────────────────────────────────────
const jsx = `// ${id}.jsx — generated by scripts/export-doc.js from a scene document.
// Do not hand-edit. Re-export from ui_kits/builder/ (or re-run export-doc.js).
// Renders the document below via motion/render-doc.jsx — the same runtime the
// visual builder uses.

const SCENE_DOC = ${docJson};

ReactDOM.createRoot(document.getElementById('root')).render(
  <Stage width={1280} height={720} duration={SCENE_DOC.duration} background="var(--bg-canvas)">
    <RenderDoc doc={SCENE_DOC} />
  </Stage>
);
`;

// ── Emit HTML ──────────────────────────────────────────────────────────
// Integrity hashes copied verbatim from motion/_scene-template.html (Hard rule 3).
const html = `<!doctype html>
<html lang="${doc.language === 'no' ? 'no' : 'en'}">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Manimo — ${title}</title>
<link rel="stylesheet" href="../../colors_and_type.css"/>
<style>
  body { margin: 0; background: var(--bg-canvas); overflow: hidden; }
</style>
<script src="https://unpkg.com/react@18.3.1/umd/react.development.js" integrity="sha384-hD6/rw4ppMLGNu3tX5cjIb+uRZ7UkRJ6BPkLpg4hAu/6onKUg4lLsHAs9EBPT82L" crossorigin="anonymous"></script>
<script src="https://unpkg.com/react-dom@18.3.1/umd/react-dom.development.js" integrity="sha384-u6aeetuaXnQ38mYT8rp6sbXaQe3NL9t+IBXmnYxwkUI2Hw4bsp2Wvmx4yRQF1uAm" crossorigin="anonymous"></script>
<script src="https://unpkg.com/@babel/standalone@7.29.0/babel.min.js" integrity="sha384-m08KidiNqLdpJqLq95G/LEi8Qvjl/xUYll3QILypMoQ65QorJ9Lvtp2RXYGBFj1y" crossorigin="anonymous"></script>
</head>
<body>
<div id="root"></div>
<script type="text/babel" data-presets="react" src="../animations.jsx"></script>
<script type="text/babel" data-presets="react" src="../manimo-motion.jsx"></script>
<script type="text/babel" data-presets="react" src="../registry.js"></script>
<script type="text/babel" data-presets="react" src="../render-doc.jsx"></script>
<script type="text/babel" data-presets="react" src="${id}.jsx"></script>
<script src="../scene-nav.js" defer></script>
</body>
</html>
`;

const outDir = join(ROOT, 'motion', subject);
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
const jsxPath = join(outDir, `${id}.jsx`);
const htmlPath = join(outDir, `${id}.html`);
writeFileSync(jsxPath, jsx);
writeFileSync(htmlPath, html);

// ── Upsert manifest ────────────────────────────────────────────────────
let manifestNote = '(manifest left untouched — --no-manifest)';
if (opts.manifest) {
  const manifestPath = join(ROOT, 'motion', 'scene-manifest.json');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  const scenes = manifest.scenes || [];
  const idx = scenes.findIndex((s) => s.id === id);
  const prev = idx === -1 ? {} : scenes[idx];
  const entry = {
    id,
    file: `${id}.jsx`,
    html: `${id}.html`,
    title,
    eyebrow: (doc.chrome && doc.chrome.eyebrow) || prev.eyebrow || '',
    topic: doc.topic || prev.topic || title,
    duration,
    language: doc.language || prev.language || 'en',
    prerequisites: prev.prerequisites || [],
    concepts: prev.concepts || [],
    subject_id: subject,
  };
  const chapter = opts.chapter != null ? opts.chapter
    : (doc.chapter_number != null ? doc.chapter_number : prev.chapter_number);
  if (chapter != null) entry.chapter_number = chapter;

  if (idx === -1) scenes.push(entry);
  else scenes[idx] = entry;
  manifest.scenes = scenes;
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
  manifestNote = idx === -1 ? 'manifest: added new entry' : 'manifest: updated existing entry';
}

console.log(`✓ Exported scene "${id}" (${subject})`);
console.log(`  ${jsxPath.replace(ROOT + '/', '')}`);
console.log(`  ${htmlPath.replace(ROOT + '/', '')}`);
console.log(`  ${manifestNote}`);
console.log(`\nPreview:  http://localhost:3000/motion/${subject}/${id}.html`);
console.log(`Snapshot: node scripts/snapshot-scene.js motion/${subject}/${id}.html --frames 4`);
