-- Seed TMA4411 (Matematikk 2B). Mirrors ADE-seed-mønsteret.
-- Faget er upublisert (published default false) til innholdet er kvalitetssikret.

-- 1. Subject ----------------------------------------------------------------
insert into public.subjects (id, code, title, description, icon, position)
values (
  'mat2b',
  'TMA4411',
  'Matematikk 2B',
  'Eksamensguide for TMA4411 — vektorrom, lineærtransformasjoner, indreproduktrom, lineære og numeriske differensialligninger, samt grenser, derivasjon og ekstremalpunkter for funksjoner av flere variable.',
  'sigma',
  20
)
on conflict (id) do update
set code = excluded.code,
    title = excluded.title,
    description = excluded.description,
    icon = excluded.icon,
    position = excluded.position;

-- Idempotens: tørk og reinsert mat2b-spesifikt innhold.
delete from public.quiz_pool where subject_id = 'mat2b';
delete from public.chapters where subject_id = 'mat2b';

-- 2. Chapters ----------------------------------------------------------------
insert into public.chapters (subject_id, chapter_number, title, icon, intro, position)
values
  ('mat2b', 1, 'Vektorrom', 'layers',
   'Vektorrom og underrom, lineærkombinasjoner, spenn, lineær uavhengighet, basis og dimensjon. Bygger ut R^n til abstrakte rom som polynomer P_n og matriserommet M_{m×n}.',
   0),
  ('mat2b', 2, 'Lineærtransformasjoner', 'shuffle',
   'Lineærtransformasjoner mellom vektorrom, kjerne og rekkevidde, rangteoremet, koordinatvektorer, matriserepresentasjon og basisbytte. Indreprodukt og projeksjon i R^n.',
   1),
  ('mat2b', 3, 'Indreproduktrom', 'compass',
   'Generelle indreproduktrom, ortogonale og ortonormale mengder, Gram–Schmidt-prosessen, projeksjon på underrom og beste approksimasjon. Ortogonalt komplement.',
   2),
  ('mat2b', 4, 'Differensialligninger', 'activity',
   'Diagonalisering og lineære systemer av differensialligninger, lineære 2.ordens-ligninger. Numerikk: Euler, trapes/Crank–Nicolson, Runge–Kutta med Butcher-tablå, og ordens-/feilanalyse.',
   3),
  ('mat2b', 5, 'Funksjoner og derivasjon', 'trending-up',
   'Skalar- og vektorfunksjoner i flere variable, mengder og følger i R^n, grenser og kontinuitet. Partielle deriverte, retningsderivert, gradient, deriverbarhet, linearisering og middelverdisetningen.',
   4),
  ('mat2b', 6, 'Ekstremalpunkter', 'target',
   'Lokale og globale ekstremalpunkter for funksjoner av flere variable. Kritiske punkt, Hesse-matrise, andrederiverttesten og søk på rand av lukkede begrensede områder.',
   5);

-- 3. Formulas ---------------------------------------------------------------
with c as (
  select id, chapter_number from public.chapters where subject_id = 'mat2b'
)
insert into public.chapter_formulas (chapter_id, position, title, formula, explanation, importance)
select c.id, x.position, x.title, x.formula, x.explanation, x.importance
from c
join (values
  -- Chapter 1: Vektorrom
  (1, 0, 'Lineærkombinasjon',
    'v = c_1 v_1 + c_2 v_2 + \cdots + c_n v_n',
    'En vektor v er en lineærkombinasjon av v_1, …, v_n dersom det finnes skalarer c_i slik at likheten holder.',
    'Høy'),
  (1, 1, 'Spenn',
    '\operatorname{Span}\{v_1,\ldots,v_n\} = \{c_1 v_1 + \cdots + c_n v_n \mid c_i \in \mathbb{R}\}',
    'Spennet er mengden av alle lineærkombinasjoner. Det er alltid et underrom av det omsluttende vektorrommet.',
    'Høy'),
  (1, 2, 'Test for lineær uavhengighet',
    'c_1 v_1 + \cdots + c_n v_n = 0 \;\Longrightarrow\; c_1=\cdots=c_n=0',
    '{v_1, …, v_n} er lineært uavhengige hvis den eneste lineærkombinasjonen som gir nullvektoren er den trivielle.',
    'Høy'),
  (1, 3, 'Underroms-test',
    '0 \in U,\;\; u+v \in U,\;\; cu \in U',
    'En ikke-tom delmengde U ⊆ V er et underrom hvis den inneholder nullvektoren og er lukket under addisjon og skalarmultiplikasjon.',
    'Høy'),
  (1, 4, 'Dimensjonen av P_n',
    '\dim \mathbb{P}_n = n + 1',
    'Polynomer av grad høyst n har basisen {1, x, x^2, …, x^n} — totalt n+1 elementer.',
    'Middels'),
  (1, 5, 'Dimensjonen av matriserommet',
    '\dim \mathcal{M}_{m\times n}(\mathbb{R}) = m\,n',
    'Standardbasisen består av matrisene E_{ij} som har 1 i posisjon (i,j) og 0 ellers — m·n elementer.',
    'Middels'),
  (1, 6, 'Antall basisvektorer i R^n',
    '\dim \mathbb{R}^n = n',
    'Standardbasisen {e_1, …, e_n} har n vektorer. Enhver basis for R^n har derfor nøyaktig n vektorer.',
    'Høy'),
  (1, 7, 'Dimensjonsformel for sum av underrom',
    '\dim(U+W) = \dim U + \dim W - \dim(U\cap W)',
    'Sammenhengen mellom dimensjonene til to underrom, deres snitt og sum.',
    'Lav'),
  -- Chapter 2: Lineærtransformasjoner
  (2, 0, 'Linearitet',
    'T(au + bv) = a\,T(u) + b\,T(v)',
    'Definisjonen av en lineærtransformasjon: bevarer addisjon og skalarmultiplikasjon. Ekvivalent med T(u+v)=T(u)+T(v) og T(cu)=cT(u).',
    'Høy'),
  (2, 1, 'Rangteoremet',
    '\dim(\operatorname{Ker} T) + \dim(\operatorname{Range} T) = \dim V',
    'For en lineærtransformasjon T : V → W er nulliteten pluss rangen lik dimensjonen til definisjonsrommet.',
    'Høy'),
  (2, 2, 'Koordinatvektor i basis B',
    '[v]_B = \begin{bmatrix} c_1\\ \vdots \\ c_n \end{bmatrix}\;\text{der}\; v = c_1 b_1 + \cdots + c_n b_n',
    'Hvis B={b_1,…,b_n} er en basis er koordinatene c_i entydige.',
    'Høy'),
  (2, 3, 'Matriserepresentasjon',
    '[T(v)]_B = [T]_B\, [v]_B',
    '[T]_B er matrisen med kolonnene [T(b_1)]_B, …, [T(b_n)]_B. Lar oss regne på T som en vanlig matrise.',
    'Høy'),
  (2, 4, 'Basisbytte (overgangsmatrise)',
    '[v]_C = P_{C\leftarrow B}\, [v]_B',
    'Kolonnene i P_{C←B} er koordinatvektorene [b_i]_C. Overgangsmatrisen er alltid invertibel: (P_{C←B})^{-1} = P_{B←C}.',
    'Høy'),
  (2, 5, 'Endring av matriserepresentasjon',
    '[T]_C = P_{C\leftarrow B}\, [T]_B\, P_{B\leftarrow C}',
    'Slik knyttes matriserepresentasjonene i to ulike basiser sammen.',
    'Middels'),
  (2, 6, 'Indreprodukt i R^n',
    '\langle u, v\rangle = u^\top v = \sum_{i=1}^{n} u_i v_i',
    'Standard prikkprodukt. Norm: ||v|| = √⟨v,v⟩. Vinkel: cos θ = ⟨u,v⟩/(||u||·||v||).',
    'Høy'),
  (2, 7, 'Projeksjon på en vektor',
    '\operatorname{proj}_v u = \frac{\langle u, v\rangle}{\langle v, v\rangle}\, v',
    'Den ortogonale projeksjonen av u ned på linjen utspent av v ≠ 0.',
    'Høy'),
  -- Chapter 3: Indreproduktrom
  (3, 0, 'Aksiomene for indreprodukt',
    '\langle u,v\rangle = \overline{\langle v,u\rangle},\; \langle au+bw, v\rangle = a\langle u,v\rangle + b\langle w,v\rangle,\; \langle v,v\rangle \ge 0',
    'Symmetri (eller konjugert symmetri), linearitet i første argument, og positiv definit (=0 kun for v=0).',
    'Høy'),
  (3, 1, 'Norm fra indreprodukt',
    '\|v\| = \sqrt{\langle v, v\rangle}',
    'Indreprodukt-rommet får automatisk en norm som tilfredsstiller trekantulikheten.',
    'Høy'),
  (3, 2, 'Cauchy–Schwarz-ulikheten',
    '\lvert\langle u, v\rangle\rvert \le \|u\|\,\|v\|',
    'Likhet hvis og bare hvis u og v er lineært avhengige.',
    'Høy'),
  (3, 3, 'Pytagoras i indreproduktrom',
    'u \perp v \;\Longrightarrow\; \|u+v\|^2 = \|u\|^2 + \|v\|^2',
    'Holder i ethvert indreproduktrom; generaliseringen av Pytagoras til vektorer.',
    'Middels'),
  (3, 4, 'Gram–Schmidt',
    'w_k = v_k - \sum_{j=1}^{k-1} \frac{\langle v_k, w_j\rangle}{\langle w_j, w_j\rangle} w_j',
    'Konstruerer en ortogonal basis {w_1,…,w_n} fra en lineært uavhengig mengde {v_1,…,v_n}. Normaliser deretter for ortonormal basis.',
    'Høy'),
  (3, 5, 'Projeksjon på underrom (ortonormal basis)',
    '\operatorname{proj}_W v = \sum_{i=1}^{k} \langle v, e_i\rangle\, e_i',
    'Når {e_1,…,e_k} er en ortonormal basis for W. Med ortogonal basis må man dele på ⟨w_i,w_i⟩.',
    'Høy'),
  (3, 6, 'Beste approksimasjonsteorem',
    '\|v - \operatorname{proj}_W v\| \le \|v - w\|\;\;\forall w \in W',
    'proj_W v er den vektoren i W som ligger nærmest v — likhet bare for w = proj_W v.',
    'Høy'),
  (3, 7, 'Ortogonalt komplement',
    'W^{\perp} = \{u \in V \mid \langle u, w\rangle = 0\;\forall w \in W\}',
    'W^⊥ er alltid et underrom. Det gjelder V = W ⊕ W^⊥ og (W^⊥)^⊥ = W når V er endeligdimensjonalt.',
    'Høy'),
  (3, 8, 'Ortonormal basis (Kronecker)',
    '\langle e_i, e_j\rangle = \delta_{ij}',
    'δ_ij er 1 hvis i=j og 0 ellers. Lar oss skrive v = Σ ⟨v,e_i⟩ e_i.',
    'Middels'),
  -- Chapter 4: Differensialligninger
  (4, 0, 'Diagonalisering',
    'A = P D P^{-1}',
    'A er diagonaliserbar hvis det finnes en invertibel P og en diagonal D slik at likheten holder. Kolonnene i P er egenvektorer; diagonalen i D er egenverdier.',
    'Høy'),
  (4, 1, 'Løsning av lineært system y'' = A y',
    'y(t) = c_1 e^{\lambda_1 t} v_1 + c_2 e^{\lambda_2 t} v_2 + \cdots + c_n e^{\lambda_n t} v_n',
    'Her er λ_i egenverdier og v_i tilhørende egenvektorer av A. Konstantene bestemmes av initialverdier.',
    'Høy'),
  (4, 2, 'Karakteristisk ligning (2. ordens)',
    'a r^2 + b r + c = 0',
    'For ay''''+by''+cy = 0. To distinkte røtter r_1, r_2 gir y = C_1 e^{r_1 t} + C_2 e^{r_2 t}; dobbeltrot r gir y=(C_1+C_2 t)e^{rt}; komplekse røtter α±iβ gir e^{αt}(C_1 cos βt + C_2 sin βt).',
    'Høy'),
  (4, 3, 'Eulers metode (eksplisitt)',
    'u_{n+1} = u_n + h\, f(t_n, u_n)',
    'Enkleste eksplisitte ettstegsmetode. Global feil O(h) — første orden.',
    'Høy'),
  (4, 4, 'Implisitt (bakover) Euler',
    'u_{n+1} = u_n + h\, f(t_{n+1}, u_{n+1})',
    'Krever løsning av en (vanligvis ikke-lineær) ligning i u_{n+1}. Stabilitetsvennlig for stive problemer. Global feil O(h).',
    'Middels'),
  (4, 5, 'Trapesmetoden / Crank–Nicolson',
    'u_{n+1} = u_n + \tfrac{h}{2}\bigl(f(t_n,u_n) + f(t_{n+1}, u_{n+1})\bigr)',
    'Implisitt, andre orden. Symmetrisk gjennomsnitt av f i endepunktene.',
    'Høy'),
  (4, 6, 'Generell Runge–Kutta-metode',
    'u_{n+1} = u_n + h \sum_{i=1}^{s} b_i K_i,\quad K_i = f\!\left(t_n + c_i h,\; u_n + h\sum_{j=1}^{s} a_{ij} K_j\right)',
    'Butcher-tablået oppsummerer hele metoden ved å plassere knutene c og koeffisientene a_{ij} i en blokk øverst og vektene b_i på en linje under. Eksplisitt ⇔ A er strengt nedre triangulær.',
    'Høy'),
  (4, 7, 'Sammenheng lokal/global feil',
    '\text{lokal feil } O(h^{p+1}) \;\Longrightarrow\; \text{global feil } O(h^p)',
    'En metode av orden p har global avbruddsfeil av orden p.',
    'Høy'),
  (4, 8, 'Konsistens av Runge–Kutta',
    '\sum_{i=1}^{s} b_i = 1',
    'Nødvendig betingelse for at metoden er konsistent (orden minst 1).',
    'Middels'),
  -- Chapter 5: Funksjoner og derivasjon
  (5, 0, 'Partiell derivert (definisjon)',
    '\frac{\partial f}{\partial x}(a,b) = \lim_{h\to 0} \frac{f(a+h, b) - f(a,b)}{h}',
    'Den vanlige deriverte av f når alle andre variable holdes konstante. Tilsvarende for ∂f/∂y.',
    'Høy'),
  (5, 1, 'Gradient',
    '\nabla f = \left(\frac{\partial f}{\partial x_1},\,\frac{\partial f}{\partial x_2},\,\ldots,\,\frac{\partial f}{\partial x_n}\right)',
    'Vektoren av alle partielle deriverte. Peker i retningen f vokser raskest, og lengden er den maksimale stigningsraten.',
    'Høy'),
  (5, 2, 'Retningsderivert',
    'D_{\mathbf{u}} f(\mathbf{a}) = \nabla f(\mathbf{a}) \cdot \mathbf{u}',
    'Forutsetter at u er en enhetsvektor og at f er deriverbar i a. Gir endringsraten i retning u.',
    'Høy'),
  (5, 3, 'Maksimal retningsderivert',
    '\max_{\|\mathbf{u}\|=1} D_{\mathbf{u}} f(\mathbf{a}) = \|\nabla f(\mathbf{a})\|',
    'Maksimum oppnås når u = ∇f/||∇f||. Minimum (=−||∇f||) i motsatt retning.',
    'Høy'),
  (5, 4, 'Linearisering',
    'L(x, y) = f(a,b) + f_x(a,b)(x-a) + f_y(a,b)(y-b)',
    'Den lineære funksjonen som best approksimerer f nær (a,b). Grafen er tangentplanet til z = f(x,y).',
    'Høy'),
  (5, 5, 'Tangentplan',
    'z = f(a,b) + f_x(a,b)(x-a) + f_y(a,b)(y-b)',
    'Tangentplanet til flaten z=f(x,y) i punktet (a,b,f(a,b)). Eksisterer når f er deriverbar i (a,b).',
    'Middels'),
  (5, 6, 'Kjerneregelen langs en kurve',
    '\frac{d}{dt} f(x(t), y(t)) = f_x\, x''(t) + f_y\, y''(t) = \nabla f \cdot \mathbf{r}''(t)',
    'Derivasjon av en sammensatt funksjon langs en parametrisert kurve r(t)=(x(t),y(t)).',
    'Høy'),
  (5, 7, 'Deriverbar ⇒ kontinuerlig',
    'f\ \text{deriverbar i } \mathbf{a} \;\Longrightarrow\; f\ \text{kontinuerlig i } \mathbf{a}',
    'Implikasjonen går bare én vei. Eksistens av partielle deriverte alene er ikke nok for deriverbarhet.',
    'Middels'),
  (5, 8, 'Tilstrekkelig betingelse for deriverbarhet',
    'f_x,\, f_y\ \text{kontinuerlige nær } \mathbf{a} \;\Longrightarrow\; f\ \text{deriverbar i } \mathbf{a}',
    'Praktisk kriterium: hvis alle partielle deriverte er kontinuerlige er funksjonen automatisk deriverbar.',
    'Middels'),
  -- Chapter 6: Ekstremalpunkter
  (6, 0, 'Kritisk punkt',
    '\nabla f(\mathbf{a}) = \mathbf{0}',
    'I et indre punkt der f er deriverbar og har ekstremum må gradienten være null. Disse kandidatpunktene kalles kritiske eller stasjonære punkter.',
    'Høy'),
  (6, 1, 'Hesse-matrisen (to variable)',
    'H_f = \begin{bmatrix} f_{xx} & f_{xy} \\ f_{xy} & f_{yy} \end{bmatrix}',
    'Matrisen av andrederiverte. Symmetrisk når blandede deriverte er kontinuerlige (Schwarz/Clairaut).',
    'Høy'),
  (6, 2, 'Diskriminant',
    'D = f_{xx}\, f_{yy} - f_{xy}^{\,2} = \det H_f',
    'Determinanten til Hesse-matrisen, brukes i andrederiverttesten.',
    'Høy'),
  (6, 3, 'Andrederiverttest — lokalt minimum',
    'D > 0\;\text{og}\; f_{xx} > 0 \;\Longrightarrow\; \text{lokalt minimum}',
    'Hesse er positiv definit; f krummer oppover i alle retninger.',
    'Høy'),
  (6, 4, 'Andrederiverttest — lokalt maksimum',
    'D > 0\;\text{og}\; f_{xx} < 0 \;\Longrightarrow\; \text{lokalt maksimum}',
    'Hesse er negativ definit; f krummer nedover i alle retninger.',
    'Høy'),
  (6, 5, 'Andrederiverttest — sadelpunkt',
    'D < 0 \;\Longrightarrow\; \text{sadelpunkt}',
    'Hesse har egenverdier av motsatt fortegn. Ingen ekstremum.',
    'Høy'),
  (6, 6, 'Andrederiverttest — ubestemt',
    'D = 0 \;\Longrightarrow\; \text{testen er inkonklusiv}',
    'Da må man undersøke funksjonen lokalt på annen måte (Taylor høyere orden, retning for retning).',
    'Middels'),
  (6, 7, 'Globale ekstrema på lukket begrenset område',
    '\text{kandidater} = \{\text{indre kritiske pkt.}\} \cup \{\text{kritiske pkt. på rand}\} \cup \{\text{hjørner}\}',
    'Ekstremalverdisetningen sikrer at maks og min eksisterer. Strategi: sjekk gradienten innenfor og parametriser/restrict på rand-stykker; sammenlign verdier.',
    'Høy')
) as x(chapter_number, position, title, formula, explanation, importance)
  on c.chapter_number = x.chapter_number;

-- 4. Concepts ---------------------------------------------------------------
with c as (
  select id, chapter_number from public.chapters where subject_id = 'mat2b'
)
insert into public.chapter_concepts (chapter_id, position, term, definition)
select c.id, x.position, x.term, x.definition
from c
join (values
  -- Chapter 1: Vektorrom
  (1, 0, 'Vektorrom',
    'Mengde V utstyrt med addisjon og skalarmultiplikasjon som tilfredsstiller de 10 vektorromaksiomene (assosiativitet, kommutativitet, eksistens av 0 og inverser, distribusjon m.fl.).'),
  (1, 1, 'Underrom',
    'Ikke-tom delmengde U ⊆ V som selv er et vektorrom under nedarvet addisjon og skalarmultiplikasjon. Tilsvarer å være lukket under addisjon og skalarmultiplikasjon og inneholde 0.'),
  (1, 2, 'Lineærkombinasjon',
    'En sum c_1 v_1 + ... + c_n v_n der c_i er skalarer fra grunnlegemet (R eller C).'),
  (1, 3, 'Spenn',
    'Mengden av alle lineærkombinasjoner av en gitt mengde vektorer. Alltid det minste underrommet som inneholder mengden.'),
  (1, 4, 'Lineært uavhengig',
    'En mengde {v_1,…,v_n} der den eneste lineærkombinasjonen som gir 0 har alle koeffisienter lik 0.'),
  (1, 5, 'Lineært avhengig',
    'En mengde som ikke er lineært uavhengig: minst én vektor kan skrives som lineærkombinasjon av de andre.'),
  (1, 6, 'Basis',
    'En lineært uavhengig mengde som utspenner hele vektorrommet. Hver vektor har da unike koordinater.'),
  (1, 7, 'Standardbasis',
    'Den naturlige basisen for et rom — for eksempel {e_1,…,e_n} i R^n eller {1,x,x²,…,xⁿ} i P_n.'),
  (1, 8, 'Dimensjon',
    'Antall vektorer i en basis. Vel-definert: alle basiser har samme antall elementer.'),
  (1, 9, 'Endeligdimensjonalt',
    'Vektorrom som har en endelig basis. Eksempler: R^n, P_n, M_{m×n}.'),
  (1, 10, 'P_n',
    'Vektorrommet av polynomer av grad høyst n med reelle koeffisienter. Har dimensjon n+1.'),
  (1, 11, 'Matriserommet M_{m×n}',
    'Vektorrommet av m×n-matriser med reelle (eller komplekse) elementer. Har dimensjon m·n.'),
  (1, 12, 'Trivielt underrom',
    'Underrommet {0} som kun består av nullvektoren. Selve V regnes også som et trivielt underrom.'),
  -- Chapter 2: Lineærtransformasjoner
  (2, 0, 'Lineærtransformasjon',
    'Avbildning T : V → W mellom vektorrom som bevarer addisjon og skalarmultiplikasjon: T(au+bv) = aT(u)+bT(v).'),
  (2, 1, 'Kjerne (Ker T)',
    'Mengden av v ∈ V slik at T(v) = 0. Alltid et underrom av V.'),
  (2, 2, 'Rekkevidde / bilde (Range T)',
    'Mengden av w ∈ W slik at w = T(v) for en eller annen v ∈ V. Alltid et underrom av W.'),
  (2, 3, 'Rang',
    'Dimensjonen til Range T. For en matrise: antall lineært uavhengige kolonner (= antall uavhengige rader).'),
  (2, 4, 'Nullitet',
    'Dimensjonen til Ker T.'),
  (2, 5, 'Injektiv',
    'T er injektiv (én-til-én) hvis T(u)=T(v) ⇒ u=v. Ekvivalent: Ker T = {0}.'),
  (2, 6, 'Surjektiv',
    'T er surjektiv (på) hvis Range T = W: hver w ∈ W treffes av en eller annen v.'),
  (2, 7, 'Isomorfi',
    'Bijektiv lineærtransformasjon. To endeligdimensjonale vektorrom er isomorfe ⇔ de har samme dimensjon.'),
  (2, 8, 'Koordinatvektor [v]_B',
    'Vektoren av skalarer som uttrykker v som lineærkombinasjon av basisvektorene i B. Avhenger av valg av basis.'),
  (2, 9, 'Matriserepresentasjon [T]_B',
    'Matrisen som virker som T når vektorene oversettes til koordinater: [T(v)]_B = [T]_B [v]_B.'),
  (2, 10, 'Overgangsmatrise',
    'Matrisen P_{C←B} som konverterer koordinater fra basis B til basis C. Kolonnene er [b_i]_C.'),
  (2, 11, 'Indreprodukt i R^n',
    'Standard prikkprodukt ⟨u,v⟩ = u^T v. Indusert norm: ||v|| = √⟨v,v⟩.'),
  (2, 12, 'Ortogonal',
    'To vektorer u, v er ortogonale dersom ⟨u,v⟩ = 0. I R^n: de står normalt på hverandre.'),
  -- Chapter 3: Indreproduktrom
  (3, 0, 'Indreprodukt',
    'En avbildning ⟨·,·⟩ : V×V → R som er symmetrisk, lineær i første argument og positiv definit. Generaliserer prikkproduktet.'),
  (3, 1, 'Indreproduktrom',
    'Vektorrom utstyrt med et indreprodukt. Får automatisk norm og avstand.'),
  (3, 2, 'Norm',
    '||v|| = √⟨v,v⟩. Måler "lengde" og oppfyller homogenitet, positivitet og trekantulikheten.'),
  (3, 3, 'Ortogonal mengde',
    'Mengde {v_1,…,v_n} der ⟨v_i,v_j⟩ = 0 for alle i ≠ j. Ortogonale ikke-null-vektorer er automatisk lineært uavhengige.'),
  (3, 4, 'Ortonormal mengde',
    'Ortogonal mengde der i tillegg ||v_i|| = 1 for alle i.'),
  (3, 5, 'Ortonormal basis',
    'Basis som samtidig er ortonormal. Da gjelder v = Σ ⟨v,e_i⟩ e_i og koordinatene leses av direkte fra indreprodukt.'),
  (3, 6, 'Ortogonalt komplement W^⊥',
    'Underrommet av alle vektorer som står ortogonalt på hele W. Det gjelder V = W ⊕ W^⊥ for endeligdimensjonale rom.'),
  (3, 7, 'Gram–Schmidt-prosessen',
    'Algoritme som transformerer en lineært uavhengig mengde {v_1,…,v_n} til en ortogonal (eller, etter normalisering, ortonormal) basis for samme spenn.'),
  (3, 8, 'Projeksjon på underrom',
    'Den entydige vektoren proj_W v ∈ W slik at v − proj_W v ∈ W^⊥. Konstrueres via formelen Σ ⟨v,e_i⟩ e_i når W har ortonormal basis.'),
  (3, 9, 'Beste approksimasjon',
    'Approksimasjonsteoremet sier at proj_W v er den vektoren i W som ligger nærmest v målt i normen indusert av indreproduktet.'),
  (3, 10, 'Cauchy–Schwarz',
    'Ulikheten |⟨u,v⟩| ≤ ||u||·||v|| som holder i alle indreproduktrom.'),
  (3, 11, 'Trekantulikheten',
    '||u+v|| ≤ ||u|| + ||v||. Følger fra Cauchy–Schwarz.'),
  (3, 12, 'Kronecker-delta',
    'δ_{ij} = 1 hvis i = j, ellers 0. Brukes til å uttrykke at en mengde er ortonormal: ⟨e_i,e_j⟩ = δ_{ij}.'),
  -- Chapter 4: Differensialligninger
  (4, 0, 'Egenverdi / egenvektor',
    'Skalaren λ og ikke-null-vektoren v slik at Av = λv. Røtter av det karakteristiske polynomet det(A − λI) = 0.'),
  (4, 1, 'Diagonaliserbar',
    'A er diagonaliserbar hvis det finnes en invertibel P og diagonal D med A = PDP⁻¹. Ekvivalent: A har n lineært uavhengige egenvektorer.'),
  (4, 2, 'Lineært system',
    'Systemet y'' = Ay (med eller uten driv). Løses ved diagonalisering eller eksponensiering av matrisen.'),
  (4, 3, 'Karakteristisk ligning',
    'For lineær 2. ordens ay''''+by''+cy=0 er det den algebraiske ligningen ar²+br+c=0. Røttenes natur bestemmer løsningsformen.'),
  (4, 4, 'Initialverdiproblem',
    'En differensialligning y'' = f(t,y) med en gitt startverdi y(t_0) = y_0. Numeriske metoder produserer approksimasjoner u_n ≈ y(t_n).'),
  (4, 5, 'Eulers metode',
    'Eksplisitt ettstegsmetode u_{n+1} = u_n + hf(t_n,u_n). Global feil O(h) — første orden.'),
  (4, 6, 'Implisitt Euler',
    'Bakover-Euler u_{n+1} = u_n + hf(t_{n+1}, u_{n+1}). Krever ligningløsning hvert steg, men er stabil for stive problemer.'),
  (4, 7, 'Trapesmetoden / Crank–Nicolson',
    'Implisitt metode u_{n+1} = u_n + (h/2)(f(t_n,u_n) + f(t_{n+1},u_{n+1})). Andre orden.'),
  (4, 8, 'Runge–Kutta-metode',
    'Familie av ettstegsmetoder med s mellom-evalueringer K_i av f. Klassisk RK4 er et eksempel.'),
  (4, 9, 'Butcher-tablå',
    'Kompakt notasjon for en RK-metode: knutene c, koeffisientene a_{ij} og vektene b_i ordnet i en tabell.'),
  (4, 10, 'Eksplisitt metode',
    'Metode der u_{n+1} kan beregnes direkte fra kjente verdier. I Butcher-tablået: A er strengt nedre triangulær.'),
  (4, 11, 'Implisitt metode',
    'Metode der u_{n+1} (eller en av K_i) opptrer på begge sider og en ligning må løses hvert steg. A har minst ett ikke-null-element på eller over diagonalen.'),
  (4, 12, 'Lokal avbruddsfeil',
    'Feilen i ett enkelt steg sammenlignet med eksakt løsning, gitt at starten av steget er eksakt. For en metode av orden p: O(h^{p+1}).'),
  (4, 13, 'Global avbruddsfeil',
    'Akkumulert feil ved tiden t etter mange steg. For en metode av orden p: O(h^p).'),
  (4, 14, 'Konvergens',
    'En metode er konvergent hvis u_n → y(t_n) når h → 0. Ekvivalent (under stabilitet): konsistens + nullstabilitet.'),
  (4, 15, 'Konsistens',
    'Lokal feil → 0 raskere enn h når h → 0. Nødvendig betingelse: Σ b_i = 1.'),
  -- Chapter 5: Funksjoner og derivasjon
  (5, 0, 'Skalarfunksjon',
    'Funksjon f : R^n → R som tar inn en vektor og gir ut en skalar.'),
  (5, 1, 'Vektorfunksjon',
    'Funksjon r : R → R^n (kurve) eller F : R^n → R^m (vektorfelt) som har vektorverdier.'),
  (5, 2, 'Definisjonsmengde',
    'Mengden av tillatte inngangsverdier. For f(x,y)=√(1−x²−y²) er definisjonsmengden enhetsskiven.'),
  (5, 3, 'Verdimengde',
    'Mengden av faktiske utgangsverdier — bildet av definisjonsmengden under f.'),
  (5, 4, 'Åpen mengde',
    'Mengde der hvert punkt har en omegn (kule) som ligger helt inni mengden. Komplementet av en lukket mengde.'),
  (5, 5, 'Lukket mengde',
    'Mengde som inneholder alle sine randpunkter. Komplementet av en åpen mengde.'),
  (5, 6, 'Følge i R^n',
    'Sekvens av vektorer (a_k)_{k=1}^{∞} i R^n. Konvergerer mot a hvis ||a_k − a|| → 0.'),
  (5, 7, 'Grense',
    'lim_{(x,y)→(a,b)} f(x,y) = L betyr at f(x,y) kan gjøres vilkårlig nær L ved å velge (x,y) tilstrekkelig nær (a,b) — uavhengig av tilnærmingsvei.'),
  (5, 8, 'Kontinuitet',
    'f er kontinuerlig i a hvis grensen i a eksisterer og er lik f(a).'),
  (5, 9, 'Partiell derivert',
    'Vanlig derivert med hensyn på én variabel, alle andre holdt konstante. Måler endringsrate langs koordinataksene.'),
  (5, 10, 'Retningsderivert',
    'D_u f(a) = ∇f(a)·u for enhetsvektor u. Generaliserer partielle deriverte til vilkårlige retninger.'),
  (5, 11, 'Gradient',
    'Vektoren ∇f av alle partielle deriverte. Står normalt på nivåkurver/-flater og peker i retning der f vokser raskest.'),
  (5, 12, 'Deriverbarhet (totalt)',
    'f er deriverbar i a hvis f(a+h) = f(a) + ∇f(a)·h + ε(h) der ε(h)/||h|| → 0. Sterkere enn eksistens av partielle deriverte.'),
  (5, 13, 'Linearisering',
    'Den lineære funksjonen L(x) = f(a) + ∇f(a)·(x−a) som best approksimerer f nær a.'),
  (5, 14, 'Tangentplan',
    'Grafen til lineariseringen — planet som tangerer flaten z = f(x,y) i punktet (a,b,f(a,b)).'),
  (5, 15, 'Middelverdisetningen',
    'For deriverbar f på linjestykket fra a til b finnes c på stykket slik at f(b) − f(a) = ∇f(c)·(b−a).'),
  -- Chapter 6: Ekstremalpunkter
  (6, 0, 'Lokalt maksimum',
    'Punkt a der f(a) ≥ f(x) for alle x i en omegn av a.'),
  (6, 1, 'Lokalt minimum',
    'Punkt a der f(a) ≤ f(x) for alle x i en omegn av a.'),
  (6, 2, 'Globalt maksimum',
    'Punkt a der f(a) ≥ f(x) for alle x i hele definisjonsmengden.'),
  (6, 3, 'Globalt minimum',
    'Punkt a der f(a) ≤ f(x) for alle x i hele definisjonsmengden.'),
  (6, 4, 'Sadelpunkt',
    'Kritisk punkt som verken er lokalt maks eller min — f vokser i én retning og avtar i en annen.'),
  (6, 5, 'Kritisk punkt / stasjonært punkt',
    'Indre punkt der ∇f = 0 (eller hvor minst én partiell derivert ikke eksisterer). Alle indre ekstrema må være kritiske punkt.'),
  (6, 6, 'Hesse-matrise',
    'Matrisen H_f av andrederiverte. Brukes til å klassifisere kritiske punkter via egenverdier eller diskriminant.'),
  (6, 7, 'Diskriminant',
    'D = f_{xx} f_{yy} − f_{xy}² for funksjoner av to variable. Sammen med fortegnet til f_{xx} avgjør den arten av kritiske punkt.'),
  (6, 8, 'Andrederiverttesten',
    'Klassifiserer kritisk punkt: D>0 og f_{xx}>0 ⇒ lok. min; D>0 og f_{xx}<0 ⇒ lok. maks; D<0 ⇒ sadelpunkt; D=0 ⇒ inkonklusiv.'),
  (6, 9, 'Ekstremalverdisetningen',
    'En kontinuerlig funksjon på en lukket og begrenset mengde antar sine globale maksimum og minimum.'),
  (6, 10, 'Randekstrema',
    'Ekstremalpunkter som ligger på randen av et lukket område. Må behandles separat fra indre kritiske punkter.'),
  (6, 11, 'Kandidatpunkter',
    'Samlingen av punkter du må sjekke for å finne globale ekstrema: indre kritiske punkt, kritiske punkt på rand-stykker, og eventuelle hjørner.')
) as x(chapter_number, position, term, definition)
  on c.chapter_number = x.chapter_number;

-- 5. Chapter quizzes (~5 per kapittel) --------------------------------------
with c as (
  select id, chapter_number from public.chapters where subject_id = 'mat2b'
)
insert into public.chapter_quiz (chapter_id, position, question, options, answer, explanation)
select c.id, x.position, x.question, x.options::jsonb, x.answer::jsonb, x.explanation
from c
join (values
  -- Chapter 1: Vektorrom
  (1, 0,
    'Hva er dimensjonen til P_3 (polynomer av grad høyst 3)?',
    '["2","3","4","uendelig"]',
    '2',
    'Standardbasisen er {1, x, x², x³} — fire elementer, så dim P_3 = 4 = 3 + 1.'),
  (1, 1,
    'Mengden {[1,0,3], [-1,1,0]} i R^3 er:',
    '["en basis for R^3","lineært avhengig","lineært uavhengig, men ikke en basis","ikke en delmengde av R^3"]',
    '2',
    'To vektorer i R^3 kan aldri utspenne hele rommet (dim 3), men siden ingen er multippel av den andre er de lineært uavhengige.'),
  (1, 2,
    'Er V = {[a,b] ∈ R² | a ≥ 0, b ≥ 0} et underrom av R²?',
    '["Ja, det er lukket under addisjon","Ja, det inneholder 0","Nei, det er ikke lukket under skalarmultiplikasjon med negative tall","Nei, det er ikke lukket under addisjon"]',
    '2',
    'Det inneholder 0 og er lukket under addisjon, men om (1,1) ∈ V er −1·(1,1) = (−1,−1) ∉ V. Et underrom må være lukket under multiplikasjon med alle skalarer.'),
  (1, 3,
    'Hvilket av disse er IKKE et vektorrom over R?',
    '["P_2 med vanlig polynomaddisjon","M_{2×2}(R)","{[a,b] ∈ R² | a + b = 0}","{[a,b] ∈ R² | a + b = 1}"]',
    '3',
    'Mengden a+b=1 inneholder ikke (0,0), og er heller ikke lukket under addisjon. De tre øvrige er klassiske eksempler på (under)rom.'),
  (1, 4,
    'En basis for U = {A ∈ M_{2×2} | A^T = −A} (skjevsymmetriske matriser) består av:',
    '["1 matrise","2 matriser","3 matriser","4 matriser"]',
    '0',
    'Skjevsymmetrisk 2×2 har formen [[0,b],[−b,0]] — én fri parameter, derfor dim U = 1.'),
  -- Chapter 2: Lineærtransformasjoner
  (2, 0,
    'Hvilket utsagn er ekvivalent med at T er injektiv?',
    '["Range T = W","Ker T = {0}","T er surjektiv","T har en matriserepresentasjon"]',
    '1',
    'For lineærtransformasjoner: T(u)=T(v) ⇔ T(u−v)=0 ⇔ u−v ∈ Ker T. Injektivitet betyr Ker T = {0}.'),
  (2, 1,
    'Rangteoremet for T : V → W sier at:',
    '["dim V = dim W","dim Ker T + dim Range T = dim V","dim Ker T = dim Range T","Range T er hele W"]',
    '1',
    'Klassisk dimensjonsregel: nullitet pluss rang er lik dimensjonen til definisjonsrommet V.'),
  (2, 2,
    'Hvor mange basiser har et endeligdimensjonalt vektorrom (av positiv dimensjon)?',
    '["Nøyaktig én","Like mange som dimensjonen","Uendelig mange","Det avhenger av indreproduktet"]',
    '2',
    'Ethvert ikke-trivielt vektorrom over R har uendelig mange basiser — enhver invertibel lineærtransformasjon sender en basis til en ny basis.'),
  (2, 3,
    'For T : M_{2×2} → M_{2×2}, T([[a,b],[c,d]]) = [[a,0],[0,d]], hva er dim Ker T?',
    '["0","1","2","4"]',
    '2',
    'Ker T = {[[0,b],[c,0]] | b,c ∈ R} — to frie parametere, derfor dim Ker T = 2. Rangen er 2 (basis: [[1,0],[0,0]], [[0,0],[0,1]]).'),
  (2, 4,
    'Hva er projeksjonen av u = (3, 4) ned på v = (1, 0)?',
    '["(0, 4)","(3, 0)","(3, 4)","(1, 0)"]',
    '1',
    'proj_v u = (⟨u,v⟩/⟨v,v⟩)v = (3/1)(1,0) = (3,0).'),
  -- Chapter 3: Indreproduktrom
  (3, 0,
    'Hva er U ∩ U^⊥ i et endeligdimensjonalt indreproduktrom?',
    '["U","U^⊥","{0}","Hele V"]',
    '2',
    'En vektor w som ligger både i U og U^⊥ må tilfredsstille ⟨w,w⟩ = 0, og dermed w = 0.'),
  (3, 1,
    'Hvilket utsagn er Cauchy–Schwarz?',
    '["||u+v|| ≤ ||u|| + ||v||","|⟨u,v⟩| ≤ ||u||·||v||","⟨u,v⟩ = ⟨v,u⟩","||u||² + ||v||² = ||u+v||²"]',
    '1',
    'Cauchy–Schwarz: prikkproduktets absoluttverdi er aldri større enn produktet av normene. Likhet ⇔ lineær avhengighet.'),
  (3, 2,
    'I Gram–Schmidt: hva er første steg gitt {v_1, v_2}?',
    '["w_1 = v_1 − v_2","w_1 = v_1","w_1 = v_1/||v_1||","w_1 = 0"]',
    '1',
    'Første vektor settes uendret: w_1 = v_1. Først ved normalisering (ortonormal basis) deles på ||w_1||.'),
  (3, 3,
    'Beste-approksimasjons-teoremet sier at:',
    '["proj_W v er nærmeste vektor i W","proj_W v ligger alltid i W^⊥","proj_W v har minst mulig norm","proj_W v = v"]',
    '0',
    '||v − proj_W v|| ≤ ||v − w|| for alle w ∈ W. Likhet bare når w = proj_W v.'),
  (3, 4,
    'Med indreproduktet ⟨f,g⟩ = f(0)g(0)+f(1)g(1)+f(2)g(2) på P_2: hva er ⟨1, x⟩?',
    '["0","1","3","6"]',
    '2',
    '1·0 + 1·1 + 1·2 = 3. Funksjonen 1 har verdiene (1,1,1); x har verdiene (0,1,2).'),
  -- Chapter 4: Differensialligninger
  (4, 0,
    'Eulers metode u_{n+1} = u_n + h·f(t_n, u_n) er:',
    '["implisitt, andre orden","eksplisitt, første orden","implisitt, første orden","eksplisitt, andre orden"]',
    '1',
    'u_{n+1} regnes direkte fra kjente størrelser — eksplisitt. Global feil er O(h), altså første orden.'),
  (4, 1,
    'En Runge–Kutta-metode er eksplisitt hvis Butcher-matrisen A er:',
    '["diagonal","symmetrisk","strengt nedre triangulær","strengt øvre triangulær"]',
    '2',
    'Eksplisitt: hver K_i avhenger kun av K_1,…,K_{i−1}, dvs. a_{ij}=0 for j ≥ i. A er strengt nedre triangulær.'),
  (4, 2,
    'En metode har lokal avbruddsfeil O(h^4). Hva er global orden?',
    '["1","2","3","4"]',
    '2',
    'Global feil = lokal feil / h. O(h^{p+1}) lokalt ⇒ O(h^p) globalt. Her: p = 3.'),
  (4, 3,
    'Trapesmetoden u_{n+1} = u_n + (h/2)(f(t_n,u_n)+f(t_{n+1},u_{n+1})) er:',
    '["eksplisitt, første orden","eksplisitt, andre orden","implisitt, første orden","implisitt, andre orden"]',
    '3',
    'f(t_{n+1}, u_{n+1}) på høyresiden gjør den implisitt; symmetrien gir andre orden.'),
  (4, 4,
    'Systemet y'' = Ay har egenverdiene 1 og 2 og tilhørende egenvektorer v_1, v_2. Generell løsning:',
    '["y = c_1 v_1 + c_2 v_2","y = (c_1 + c_2 t) e^t","y = c_1 e^t v_1 + c_2 e^{2t} v_2","y = c_1 e^{1+2} (v_1 + v_2)"]',
    '2',
    'For diagonaliserbar A er løsningen en sum c_i e^{λ_i t} v_i.'),
  -- Chapter 5: Funksjoner og derivasjon
  (5, 0,
    'I hvilken retning vokser f raskest i punktet a?',
    '["I retning av nullvektoren","Vinkelrett på ∇f(a)","I retning av ∇f(a)","Tilfeldig"]',
    '2',
    'Maksimal retningsderivert oppnås når enhetsvektoren u er parallell med ∇f(a) — størrelse ||∇f(a)||.'),
  (5, 1,
    'Hvilken implikasjon er korrekt?',
    '["Kontinuerlig ⇒ deriverbar","Partielle deriverte eksisterer ⇒ deriverbar","Deriverbar ⇒ kontinuerlig","Partielle deriverte eksisterer ⇒ kontinuerlig"]',
    '2',
    'I flere variable: deriverbarhet ⇒ kontinuitet, men ikke omvendt. Eksistens av partielle deriverte er ikke nok for verken deriverbarhet eller kontinuitet.'),
  (5, 2,
    'For f(x,y) = xy + y³: hva er ∂f/∂y i (1,2)?',
    '["x + 3y² = 13","x + 3y² = 14","2y = 4","y² = 4"]',
    '0',
    '∂f/∂y = x + 3y². Innsatt: 1 + 3·4 = 13.'),
  (5, 3,
    'Linearisering av f i punktet (a,b) er funksjonen:',
    '["L = f(a,b)","L = f_x(a,b)x + f_y(a,b)y","L = f(a,b) + f_x(a,b)(x-a) + f_y(a,b)(y-b)","L = ∇f · (x,y)"]',
    '2',
    'Lineariseringen er førsteordens-Taylor: konstantleddet f(a,b) pluss lineær del med deriverte i utviklingspunktet.'),
  (5, 4,
    'For f(x,y) = xe^y + z² i punktet (1, ln2, 1/2) er ∇f lik:',
    '["(e^y, xe^y, 2z) = (2, 2, 1)","(e^y, x e^y, 0) = (2, 2, 0)","(2x, 2y, 2z)","(1, 1, 1)"]',
    '0',
    '∂_x = e^y = 2, ∂_y = x e^y = 2, ∂_z = 2z = 1. Maksimal retning er (2,2,1)/||(2,2,1)|| = (2,2,1)/3.'),
  -- Chapter 6: Ekstremalpunkter
  (6, 0,
    'I et lokalt ekstremum (indre punkt der f er deriverbar) gjelder:',
    '["f = 0","∇f = 0","Hesse-matrisen er null","f_{xx} > 0"]',
    '1',
    'Fermats setning i flere variable: alle partielle deriverte må være null. Punktet kalles da kritisk eller stasjonært.'),
  (6, 1,
    'D > 0 og f_{xx} < 0 i et kritisk punkt betyr:',
    '["lokalt minimum","lokalt maksimum","sadelpunkt","ubestemt"]',
    '1',
    'D > 0 sikrer at testen avgjør; f_{xx} < 0 (Hesse negativ definit) gir lokalt maksimum.'),
  (6, 2,
    'D < 0 i et kritisk punkt betyr:',
    '["lokalt minimum","lokalt maksimum","sadelpunkt","ubestemt"]',
    '2',
    'Hesse har egenverdier av motsatt fortegn — f vokser i én retning og avtar i en annen.'),
  (6, 3,
    'For f(x,y) = x² + y² − xy + x + y, hva er det entydige kritiske punktet?',
    '["(0, 0)","(-1, -1)","(1, 1)","(-1, 0)"]',
    '1',
    '∇f = (2x − y + 1, 2y − x + 1) = 0 gir 2x − y = −1, 2y − x = −1. Løsning: x = y = −1.'),
  (6, 4,
    'Ekstremalverdisetningen krever at definisjonsområdet er:',
    '["åpent","lukket og begrenset","sammenhengende","konvekst"]',
    '1',
    'En kontinuerlig funksjon på en kompakt (lukket og begrenset) mengde i R^n antar sine globale ekstrema.')
) as x(chapter_number, position, question, options, answer, explanation)
  on c.chapter_number = x.chapter_number;

-- 6. Quiz pool (eksamensstil og blandet drill) ------------------------------
insert into public.quiz_pool (subject_id, position, question, options, answer, chapter_number, part, source, explanation)
values
  ('mat2b', 0,
    'Ligger x = (1, 1, −2) i Span{u, v} der u = (2, −1, 4) og v = (3, 0, −1)?',
    '["Ja","Nei","Bare hvis vi tillater komplekse koeffisienter","Kan ikke avgjøres"]'::jsonb,
    '1'::jsonb,
    1, null, 'Plenum 1 oppg. 1',
    'Sett opp au + bv = x: 2a+3b=1, −a=1, 4a−b=−2. Fra (2) a=−1; (1) gir b=1; sjekker (3): −4−1=−5 ≠ −2. Ingen løsning, så x ∉ Span{u,v}.'),
  ('mat2b', 1,
    'Anta at u, v, w er lineært uavhengige. Er {u+v, v+w, u+w} lineært uavhengige?',
    '["Aldri","Ja, alltid","Bare når u, v, w er ortogonale","Bare i R^3"]'::jsonb,
    '1'::jsonb,
    1, null, 'Plenum 1 oppg. 2',
    'a(u+v)+b(v+w)+c(u+w)=0 ⇒ (a+c)u+(a+b)v+(b+c)w=0. Uavhengighet av u,v,w gir a+c=a+b=b+c=0 med entydig løsning a=b=c=0.'),
  ('mat2b', 2,
    'Spans{x+1, x²} og Span{x² − 3x − 3, x² + x + 1} i P_∞ er:',
    '["forskjellige","like","det ene inneholdt i det andre, men ikke omvendt","kan ikke avgjøres"]'::jsonb,
    '1'::jsonb,
    1, null, 'Plenum 1 oppg. 4',
    'x²−3x−3 = x² − 3(x+1); x²+x+1 = x² + (x+1). Begge ligger i Span{x+1, x²}. Omvendt: differensen gir 4(x+1) ⇒ x+1, og dermed også x². Spanene er like.'),
  ('mat2b', 3,
    'Mengden {[1,0,3], [−1,1,0], [1,1,6]} i R^3 er:',
    '["en basis","lineært avhengig","ortogonal","spenner ut bare et plan"]'::jsonb,
    '1'::jsonb,
    1, null, 'Plenum 2 oppg. 1c',
    '[1,1,6] = 2·[1,0,3] + [−1,1,0] (sjekk: 2−1=1, 0+1=1, 6+0=6). Tredje vektor er en lineærkombinasjon av de to første, så mengden er lineært avhengig.'),
  ('mat2b', 4,
    'Dimensjonen av U = {A ∈ M_{2×2} | A^T = −A} er:',
    '["1","2","3","4"]'::jsonb,
    '0'::jsonb,
    1, null, 'Plenum 2 oppg. 2b',
    'Skjevsymmetrisk 2×2 har form [[0,b],[−b,0]]. Én fri parameter, så dim U = 1.'),
  ('mat2b', 5,
    'T : P_2 → R^2 gitt ved T(p) = (p(1), p(0))^T. En basis for Ker T består av:',
    '["{1}","{x}","{x² − x}","{1, x}"]'::jsonb,
    '2'::jsonb,
    2, null, 'Plenum 2 oppg. 3b',
    'p(x) = ax² + bx + c i Ker T krever p(0)=c=0 og p(1)=a+b=0, så p(x)=a(x²−x). Basis: {x²−x}.'),
  ('mat2b', 6,
    'T : M_{2×2} → M_{2×2}, T([[a,b],[c,d]]) = [[a,0],[0,d]]. Er T injektiv og/eller surjektiv?',
    '["Begge","Verken/eller","Injektiv, ikke surjektiv","Surjektiv, ikke injektiv"]'::jsonb,
    '1'::jsonb,
    2, null, 'Plenum 2 oppg. 4',
    'Ker T = {[[0,b],[c,0]]} ≠ {0}, så ikke injektiv. Range T = diagonalmatriser ≠ M_{2×2}, så ikke surjektiv.'),
  ('mat2b', 7,
    'For T over: hva er rangen av T?',
    '["0","1","2","4"]'::jsonb,
    '2'::jsonb,
    2, null, 'Plenum 2 oppg. 4',
    'Range T er diagonalmatrisene — utspent av [[1,0],[0,0]] og [[0,0],[0,1]]. Dim = 2.'),
  ('mat2b', 8,
    'For T : V → V med T(u)=2u−4w, T(v)=u+v+w, T(w)=−2u+v/2 i basis B={u,v,w}, kolonne 1 i [T]_B er:',
    '["(2, 0, -4)^T","(2, 1, -2)^T","(1, 1, 1)^T","(-4, 0, 2)^T"]'::jsonb,
    '0'::jsonb,
    2, null, 'Plenum 3 oppg. 2a',
    'Kolonne i er koordinatene til T(b_i) i basis B. T(u) = 2u + 0v + (−4)w, så kolonnen er (2,0,−4)^T.'),
  ('mat2b', 9,
    'Med indreproduktet ⟨f,g⟩ = f(0)g(0)+f(1)g(1)+f(2)g(2): hva er ⟨1−x, 1−x⟩?',
    '["1","2","3","5"]'::jsonb,
    '1'::jsonb,
    3, null, 'Plenum 3 oppg. 5',
    '1−x har verdier (1, 0, −1) i punktene 0, 1, 2. ⟨1−x, 1−x⟩ = 1² + 0² + (−1)² = 2.'),
  ('mat2b', 10,
    'Projeksjonen av q(x) = −1 + x² ned på p(x) = 1 − x med samme indreprodukt er:',
    '["−2(1 − x)","2(1 − x)","−(1 − x)/2","0"]'::jsonb,
    '0'::jsonb,
    3, null, 'Plenum 3 oppg. 5',
    'q har verdier (−1, 0, 3), p har verdier (1, 0, −1). ⟨q, p⟩ = (−1)·1 + 0 + 3·(−1) = −4. ⟨p, p⟩ = 2. proj_p q = (−4/2)·p = −2(1 − x).'),
  ('mat2b', 11,
    'For Gram–Schmidt på {1−x, −1+x²} med indreproduktet ⟨f,g⟩=f(0)g(0)+f(1)g(1)+f(2)g(2): første ortogonale vektor er w_1 =',
    '["1−x","−1+x²","1","x"]'::jsonb,
    '0'::jsonb,
    3, null, 'Plenum 4 oppg. 1',
    'Første steg i Gram–Schmidt er alltid å beholde v_1 uforandret: w_1 = 1 − x.'),
  ('mat2b', 12,
    'La W ⊆ R^n være et underrom. Hvis w ∈ W ∩ W^⊥, er w lik:',
    '["en vilkårlig vektor","0","en enhetsvektor","kun null hvis dim W > 0"]'::jsonb,
    '1'::jsonb,
    3, null, 'Plenum 4 oppg. 2',
    'w ∈ W^⊥ betyr ⟨w, w⟩ = 0 (siden w ∈ W). Positiv definit ⇒ w = 0.'),
  ('mat2b', 13,
    'Matrisen A = [[2,−1],[1/2,1/2]] har egenvektorene (1,1)^T og (2,1)^T. Egenverdiene er:',
    '["1 og 3/2","1 og 2","1/2 og 3/2","−1 og 2"]'::jsonb,
    '0'::jsonb,
    4, null, 'Plenum 4 oppg. 3a',
    'A(1,1)^T = (1,1)^T, så λ=1. A(2,1)^T = (3, 3/2)^T = (3/2)(2,1)^T, så λ = 3/2.'),
  ('mat2b', 14,
    'For y'' = Ay med A fra forrige oppgave og y(0) = (1, −1)^T, hva er konstantene (c_1, c_2) når y(t) = c_1 e^t (1,1)^T + c_2 e^{3t/2} (2,1)^T?',
    '["(3, −1)","(−3, 2)","(1, 0)","(0, −1)"]'::jsonb,
    '1'::jsonb,
    4, null, 'Plenum 4 oppg. 3b',
    'y(0) = (c_1 + 2c_2, c_1 + c_2) = (1, −1). Fra likningene: c_1 + 2c_2 = 1 og c_1 + c_2 = −1 gir c_2 = 2 og c_1 = −3. Løsningen er y(t) = −3 e^t (1,1)^T + 2 e^{3t/2} (2,1)^T.'),
  ('mat2b', 15,
    'Hvilken numerisk metode er IKKE eksplisitt?',
    '["Eulers metode","RK4","Crank–Nicolson","Modifisert Euler (Heun)"]'::jsonb,
    '2'::jsonb,
    4, null, 'Plenum 5 oppg. 1b',
    'Crank–Nicolson/trapesmetoden inkluderer f(t_{n+1}, u_{n+1}) på høyresiden — implisitt. De øvrige er eksplisitte.'),
  ('mat2b', 16,
    'Python-koden bruker oppdateringen y_new = y + (h/2)(k1+k2) med k1=f(t,y), k2=f(t+h, y+h·k1). Dette er:',
    '["Eulers metode","Heuns metode (forbedret Euler)","RK4","Bakover-Euler"]'::jsonb,
    '1'::jsonb,
    4, null, 'Plenum 5 oppg. 1b',
    'Heun = trapes-prediktor-korrektor: prediksjon med Euler, korrigering med trapes. Eksplisitt, andre orden.'),
  ('mat2b', 17,
    'Butcher-tablået for Heuns metode er:',
    '["0|0 0 / 1|1 0 / |1/2 1/2","0|0 0 / 1|0 1 / |1/2 1/2","0|1 / |1","1|0 / 0|1 / |1 0"]'::jsonb,
    '0'::jsonb,
    4, null, 'Plenum 5 oppg. 1b',
    'c=(0,1), A=[[0,0],[1,0]], b=(1/2,1/2). Strengt nedre triangulær A — eksplisitt.'),
  ('mat2b', 18,
    'Med Heun på y'' = ty², y(0)=0.5, h=0.1, ett steg: k1 = 0, k2 = 0.1·0.5² = 0.025. Hva er y_1?',
    '["0.5","0.50125","0.5025","0.625"]'::jsonb,
    '1'::jsonb,
    4, null, 'Plenum 5 oppg. 1c',
    'y_1 = 0.5 + (0.1/2)(0 + 0.025) = 0.5 + 0.00125 = 0.50125; t_1 = 0.1.'),
  ('mat2b', 19,
    'Heuns metode har global avbruddsfeil av orden:',
    '["1","2","3","4"]'::jsonb,
    '1'::jsonb,
    4, null, 'Plenum 5 oppg. 3',
    'Taylor-utvikling viser at lokal feil er O(h^3), så global feil er O(h^2). Heun er en andre-ordens metode.'),
  ('mat2b', 20,
    'En 3-stegs RK-metode med b = (1/6, 1/6, 4/6) tilfredsstiller Σ b_i =',
    '["1/3","1/2","1","2"]'::jsonb,
    '2'::jsonb,
    4, null, 'Plenum 5 oppg. 2b',
    '1/6 + 1/6 + 4/6 = 6/6 = 1. Konsistens-betingelsen er oppfylt.'),
  ('mat2b', 21,
    'For y'' = y² + t, y(0)=1, h=0.1 med en 3-stegs RK (K_1, K_2, K_3 som definert): K_1 =',
    '["0","0.5","1","2"]'::jsonb,
    '2'::jsonb,
    4, null, 'Plenum 5 oppg. 2a',
    'K_1 = f(0, 1) = 1² + 0 = 1.'),
  ('mat2b', 22,
    'Er f(x,y) = (xy + y³)/(x² + y²), f(0,0) = 0, kontinuerlig i (0,0)?',
    '["Ja","Nei, grensen finnes ikke","Nei, grensen er 1","Bare langs y-aksen"]'::jsonb,
    '1'::jsonb,
    5, null, 'Plenum 6 oppg. 1',
    'Polkoordinater: xy = r² sin θ cos θ, y³ = r³ sin³ θ. f = sin θ cos θ + r sin³ θ → sin θ cos θ = ½ sin 2θ når r → 0. Grensen avhenger av retningen, så den finnes ikke — f er ikke kontinuerlig i (0,0).'),
  ('mat2b', 23,
    'For f(x,y,z) = xe^y + z² gir gradienten i (1, ln2, 1/2):',
    '["(2, 2, 1)","(1, 1, 1)","(2, 1, 1)","(e, 2, 1/2)"]'::jsonb,
    '0'::jsonb,
    5, null, 'Plenum 6 oppg. 2',
    '∇f = (e^y, x e^y, 2z). Innsatt: (e^{ln2}, 1·e^{ln2}, 2·1/2) = (2, 2, 1).'),
  ('mat2b', 24,
    'Retningen som gir størst retningsderivert av f(x,y,z)=xe^y+z² i (1, ln2, 1/2) er:',
    '["(1,1,1)/√3","(2,2,1)/3","(2,2,1)","(1,2,1)/√6"]'::jsonb,
    '1'::jsonb,
    5, null, 'Plenum 6 oppg. 2',
    '∇f = (2,2,1), ||∇f|| = √(4+4+1) = 3. Enhetsvektoren er (2,2,1)/3.'),
  ('mat2b', 25,
    'Største verdi av D_u f i samme punkt er:',
    '["1","2","3","9"]'::jsonb,
    '2'::jsonb,
    5, null, 'Plenum 6 oppg. 2',
    'Maks D_u f = ||∇f|| = 3.'),
  ('mat2b', 26,
    'For f(x,y) = x² + y² − xy + x + y er det entydige kritiske punktet:',
    '["(0, 0)","(−1, −1)","(1, 1)","(−1/3, −1/3)"]'::jsonb,
    '1'::jsonb,
    6, null, 'Plenum 6 oppg. 3',
    '∇f = (2x − y + 1, 2y − x + 1) = 0. 2x − y = −1, 2y − x = −1 ⇒ x = y = −1.'),
  ('mat2b', 27,
    'Hesse-matrisen til f(x,y) = x² + y² − xy + x + y er:',
    '["[[1,0],[0,1]]","[[2,-1],[-1,2]]","[[2,1],[1,2]]","[[1,-1],[-1,1]]"]'::jsonb,
    '1'::jsonb,
    6, null, 'Plenum 6 oppg. 3',
    'f_xx = 2, f_yy = 2, f_xy = −1. D = 4 − 1 = 3 > 0, f_xx = 2 > 0 ⇒ kritisk punkt er lokalt minimum.'),
  ('mat2b', 28,
    'For samme f på området x≤0, y≤0, x+y≥−3 (en trekant): hvor mange indre kritiske punkter ligger i området?',
    '["0","1","2","uendelig"]'::jsonb,
    '1'::jsonb,
    6, null, 'Plenum 6 oppg. 3',
    'Det entydige kritiske punktet (−1,−1) tilfredsstiller −1 ≤ 0, −1 ≤ 0, og −1+(−1) = −2 ≥ −3. Det ligger inni området.'),
  ('mat2b', 29,
    'Verdien til f(x,y) = x²+y²−xy+x+y i punktet (−1,−1) er:',
    '["−1","0","1","3"]'::jsonb,
    '0'::jsonb,
    6, null, 'Plenum 6 oppg. 3',
    'f(−1,−1) = 1 + 1 − 1 − 1 − 1 = −1. Dette er kandidat for globalt minimum.'),
  ('mat2b', 30,
    'På randen y = 0, x ∈ [−3, 0] reduseres f til g(x) = x² + x. g har ekstremum i x =',
    '["−1/2","0","−3","−1"]'::jsonb,
    '0'::jsonb,
    6, null, 'Plenum 6 oppg. 3',
    'g''(x) = 2x + 1 = 0 ⇒ x = −1/2. g(−1/2) = 1/4 − 1/2 = −1/4 — kandidat for minimum på dette rand-stykket.'),
  ('mat2b', 31,
    'På randen x+y = −3, x ∈ [−3, 0]: substituer y = −3−x. f blir h(x) = 3x² + 9x + 6. h har ekstremum i x =',
    '["−3/2","0","−3","3"]'::jsonb,
    '0'::jsonb,
    6, null, 'Plenum 6 oppg. 3',
    'h''(x) = 6x + 9 = 0 ⇒ x = −3/2. h(−3/2) = 27/4 − 27/2 + 6 = (27 − 54 + 24)/4 = −3/4 — kandidat for randminimum.'),
  ('mat2b', 32,
    'Hjørnene i området er (0,0), (−3,0), (0,−3). f i hjørnene gir verdiene:',
    '["0, 6, 6","0, 6, −6","0, −6, −6","1, 6, 6"]'::jsonb,
    '0'::jsonb,
    6, null, 'Plenum 6 oppg. 3',
    'f(0,0)=0; f(−3,0)=9+0−0−3+0=6; f(0,−3)=0+9−0+0−3=6.'),
  ('mat2b', 33,
    'Globalt maksimum av f på det lukkede området er:',
    '["−1","0","6","−1/4"]'::jsonb,
    '2'::jsonb,
    6, null, 'Plenum 6 oppg. 3',
    'Sammenligning av kandidater: −1, −1/4, −3/4, 0, 6, 6. Maksimum er 6, antatt i (−3,0) og (0,−3).'),
  ('mat2b', 34,
    'Globalt minimum av samme f er:',
    '["−1","0","6","−3/4"]'::jsonb,
    '0'::jsonb,
    6, null, 'Plenum 6 oppg. 3',
    'Minimum av {−1, −1/4, −3/4, 0, 6, 6} er −1, antatt i det indre kritiske punktet (−1,−1).'),
  ('mat2b', 35,
    'La A være reelt diagonaliserbar med A^4 = A. Hva må gjelde for egenverdiene?',
    '["λ ∈ {0, 1}","λ ∈ {0, 1, −1}","alle reelle tall","kun komplekse"]'::jsonb,
    '0'::jsonb,
    4, null, 'Plenum 4 oppg. 4',
    'λ^4 = λ ⇒ λ(λ³ − 1) = 0. Reelle løsninger er λ = 0 og λ = 1 (λ³ = 1 har bare én reell rot). Begge tilfredsstiller λ² = λ, så A² = A.'),
  ('mat2b', 36,
    'Heuns metode brukt på y''=ty², y(0)=0.5, h=0.1, N=1 gir ifølge Python-koden ut:',
    '["0.1 0.5","0.1 0.50125","0.0 0.5","0.1 0.625"]'::jsonb,
    '1'::jsonb,
    4, null, 'Plenum 5 oppg. 1c',
    'Etter ett steg: t = 0.1, y = 0.5 + 0.00125 = 0.50125.'),
  ('mat2b', 37,
    'Approksimasjonsteoremet sier at proj_W v har minst:',
    '["||v||","||v − w||-verdien over alle w∈W","norm i W","norm i V"]'::jsonb,
    '1'::jsonb,
    3, null, 'Pensum uke 7',
    'proj_W v minimerer ||v − w|| over w ∈ W. Det er den nærmeste vektoren i W til v.'),
  ('mat2b', 38,
    'Hvilken egenskap er IKKE et krav for at U ⊆ V skal være et underrom?',
    '["0 ∈ U","lukket under addisjon","lukket under skalarmult.","U inneholder en basis for V"]'::jsonb,
    '3'::jsonb,
    1, null, 'Pensum uke 3',
    'Et underrom trenger ikke å spenne ut V. Kravene er: inneholder 0, lukket under +, lukket under ·.'),
  ('mat2b', 39,
    'Hvilken metode har orden 4 og er klassisk i ingeniørbruk?',
    '["Euler","Heun","RK4","Crank–Nicolson"]'::jsonb,
    '2'::jsonb,
    4, null, 'Pensum uke 10',
    'Klassisk Runge–Kutta (RK4) har 4 stadier og global feil O(h^4). Veldig populær balanse mellom presisjon og enkelhet.');

-- Done. Faget vil først bli synlig for brukere når noen setter
-- published = true for subject_id = 'mat2b'.
